name: haskell
synopsis: My notes on the Haskell language.

executables:
  haskell:
    main: Main.hs
    source-dirs: [src]
    # dependencies:
    #   [base, checkers, containers, random, QuickCheck, uuid, text, time, transformers]
